import { PackageRelatedItems } from './PackageRelatedItems.jsx'
import { WorkspaceDetailPanel } from './WorkspaceDetailPanel.jsx'

export function InlineWorkspace({
  activeContinuousPublish,
  actionQosControls,
  cancelingGoal,
  executing,
  goalTimeoutSec,
  goalValues,
  inlineResult,
  item,
  onActionExecute,
  onActionCancel,
  onGoalChange,
  onHistorySelect,
  onOpenExecution,
  onMessageChange,
  onRelatedSelect,
  onRequestChange,
  onServiceExecute,
  onServiceRequestQosModeChange,
  onServiceRequestQosProfileChange,
  onServiceResponseQosModeChange,
  onServiceResponseQosProfileChange,
  onTopicPublish,
  onTopicContinuousStart,
  onTopicContinuousStop,
  onTopicReset,
  onServiceActionReset,
  onTopicSubscribeStart,
  onTopicSubscribeStop,
  onTopicPublishQosModeChange,
  onTopicPublishQosProfileChange,
  onTopicSubscribeQosModeChange,
  onTopicSubscribeQosProfileChange,
  relatedItems,
  messageValues,
  requestValues,
  selectedHistoryItem,
  serviceRequestQosMode,
  serviceRequestQosProfile,
  serviceResponseQosMode,
  serviceResponseQosProfile,
  selectPublishGraphTopic,
  setGoalTimeoutSec,
  setTopicPublishName,
  setTopicPublishHz,
  setTopicSubscribeName,
  setTimeoutSec,
  topicPublishName,
  topicPublishHz,
  publishGraphTopics,
  topicPublishWarning,
  topicPublishQosMode,
  topicPublishQosProfile,
  topicSubscribeQosMode,
  topicSubscribeQosProfile,
  topicSubscribeName,
  timeoutSec,
}) {
  const showDetail = item.kind !== 'package'
  return (
    <div className="interface-inline-workspace">
      {item.kind === 'package' && (
        <PackageRelatedItems item={item} onSelect={onRelatedSelect} relatedItems={relatedItems} />
      )}
      {showDetail && (
        <WorkspaceDetailPanel
          cancelingGoal={cancelingGoal}
          actionQosControls={actionQosControls}
          activeContinuousPublish={activeContinuousPublish}
          executing={executing}
          goalTimeoutSec={goalTimeoutSec}
          goalValues={goalValues}
          inlineResult={inlineResult}
          item={item}
          onActionExecute={onActionExecute}
          onActionCancel={onActionCancel}
          onGoalChange={onGoalChange}
          onHistorySelect={onHistorySelect}
          onOpenExecution={onOpenExecution}
          onMessageChange={onMessageChange}
          onRequestChange={onRequestChange}
          onServiceExecute={onServiceExecute}
          onServiceRequestQosModeChange={onServiceRequestQosModeChange}
          onServiceRequestQosProfileChange={onServiceRequestQosProfileChange}
          onServiceResponseQosModeChange={onServiceResponseQosModeChange}
          onServiceResponseQosProfileChange={onServiceResponseQosProfileChange}
          onTopicPublish={onTopicPublish}
          onTopicContinuousStart={onTopicContinuousStart}
          onTopicContinuousStop={onTopicContinuousStop}
          onTopicReset={onTopicReset}
          onServiceActionReset={onServiceActionReset}
          onTopicSubscribeStart={onTopicSubscribeStart}
          onTopicSubscribeStop={onTopicSubscribeStop}
          onTopicPublishQosModeChange={onTopicPublishQosModeChange}
          onTopicPublishQosProfileChange={onTopicPublishQosProfileChange}
          onTopicSubscribeQosModeChange={onTopicSubscribeQosModeChange}
          onTopicSubscribeQosProfileChange={onTopicSubscribeQosProfileChange}
          messageValues={messageValues}
          requestValues={requestValues}
          selectedHistoryItem={selectedHistoryItem}
          serviceRequestQosMode={serviceRequestQosMode}
          serviceRequestQosProfile={serviceRequestQosProfile}
          serviceResponseQosMode={serviceResponseQosMode}
          serviceResponseQosProfile={serviceResponseQosProfile}
          selectPublishGraphTopic={selectPublishGraphTopic}
          setGoalTimeoutSec={setGoalTimeoutSec}
          setTopicPublishName={setTopicPublishName}
          setTopicPublishHz={setTopicPublishHz}
          setTopicSubscribeName={setTopicSubscribeName}
          setTimeoutSec={setTimeoutSec}
          topicPublishName={topicPublishName}
          topicPublishHz={topicPublishHz}
          publishGraphTopics={publishGraphTopics}
          topicPublishWarning={topicPublishWarning}
          topicPublishQosMode={topicPublishQosMode}
          topicPublishQosProfile={topicPublishQosProfile}
          topicSubscribeQosMode={topicSubscribeQosMode}
          topicSubscribeQosProfile={topicSubscribeQosProfile}
          topicSubscribeName={topicSubscribeName}
          timeoutSec={timeoutSec}
        />
      )}
    </div>
  )
}
