<?xml version="1.0"?>
<package format="3">
  <name>ros2_dashboard_dds_observer</name>
  <version>0.0.0</version>
  <description>Passive Fast DDS service endpoint QoS discovery helper.</description>
  <maintainer email="ohs9062@gmail.com">hs</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>fastrtps</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
