export function actionExecutionViewProps(state) {
  return {
    actions: state.callableActions,
    busy: state.actionGoalBusy,
    expanded: state.expanded,
    goals: state.actionGoalHistory,
    goalValues: state.goalValues,
    importableOnly: state.actionImportableOnly,
    onExecute: state.executeActionGoal,
    onFieldChange: (name, value) => state.setGoalValues((current) => ({ ...current, [name]: value })),
    onImportableOnlyChange: state.setActionImportableOnly,
    onSelect: state.setSelectedActionKey,
    onTimeoutChange: state.setGoalTimeoutSec,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    result: state.actionGoalResult,
    selected: state.selectedAction,
    selectedKey: state.selectedActionKey,
    showExpand: state.showExpand,
    qosControls: state.actionQosControls,
    modeLinked: state.actionQosModeLinked,
    onModeLinkChange: state.setActionQosModeLinked,
    timeoutSec: state.goalTimeoutSec,
    visibleActions: state.visibleCallableActions,
  }
}

export function serviceExecutionViewProps(state) {
  return {
    busy: state.serviceCallBusy,
    calls: state.serviceCallHistory,
    expanded: state.expanded,
    importableOnly: state.serviceImportableOnly,
    onExecute: state.executeServiceCall,
    onFieldChange: (name, value) => state.setRequestValues((current) => ({ ...current, [name]: value })),
    onImportableOnlyChange: state.setServiceImportableOnly,
    onRequestQosModeChange: state.setServiceRequestQosMode,
    onRequestQosProfileChange: state.setServiceRequestQosProfile,
    modeLinked: state.serviceQosModeLinked,
    onModeLinkChange: state.setServiceQosModeLinked,
    onSelect: state.setSelectedServiceKey,
    onTimeoutChange: state.setTimeoutSec,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    requestValues: state.requestValues,
    result: state.serviceCallResult,
    requestQosMode: state.serviceRequestQosMode,
    requestQosProfile: state.serviceRequestQosProfile,
    selected: state.selectedService,
    selectedKey: state.selectedServiceKey,
    services: state.callableServices,
    showExpand: state.showExpand,
    timeoutSec: state.timeoutSec,
    visibleServices: state.visibleCallableServices,
  }
}

export function topicExecutionViewProps(state) {
  return {
    activeContinuousPublish: state.activeContinuousPublish,
    busy: state.topicPublishBusy,
    expanded: state.expanded,
    history: state.visiblePublishHistory,
    importableOnly: state.topicImportableOnly,
    messageValues: state.topicMessageValues,
    messages: state.callableMessages,
    onContinuousStart: state.startSelectedContinuousTopicPublish,
    onContinuousStop: state.stopSelectedContinuousTopicPublish,
    onFieldChange: (name, value) => state.setTopicMessageValues((current) => ({ ...current, [name]: value })),
    onHzChange: state.setTopicPublishHz,
    onImportableOnlyChange: state.setTopicImportableOnly,
    onPublish: state.publishSelectedTopicMessage,
    onQosModeChange: state.setTopicQosMode,
    onQosProfileChange: state.setTopicQosProfile,
    modeLinked: state.topicQosModeLinked,
    onModeLinkChange: state.setTopicQosModeLinked,
    onResetHistory: state.resetSelectedTopicPublishHistory,
    onSelect: state.setSelectedMessageKey,
    onTopicNameChange: state.setTopicPublishName,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    publishGraphTopics: state.publishGraphTopics,
    publishHz: state.topicPublishHz,
    publishName: state.topicPublishName,
    publishResult: state.topicPublishResult,
    publishWarning: state.topicPublishWarning,
    qosMode: state.topicQosMode,
    qosProfile: state.topicQosProfile,
    selected: state.selectedMessage,
    selectedKey: state.selectedMessageKey,
    showExpand: state.showExpand,
    visibleMessages: state.visibleCallableMessages,
  }
}
