export function actionExecutionViewProps(state) {
  return {
    actions: state.callableActions,
    busy: state.actionGoalBusy,
    expanded: state.expanded,
    goals: state.actionGoalHistory,
    goalValues: state.goalValues,
    importableOnly: state.actionImportableOnly,
    onExecute: state.executeActionGoal,
    onFieldChange: (name, value) => state.setGoalValues((current) => ({ ...current, [name]: value })),
    onImportableOnlyChange: state.setActionImportableOnly,
    onSelect: state.setSelectedActionKey,
    onTimeoutChange: state.setGoalTimeoutSec,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    result: state.actionGoalResult,
    selected: state.selectedAction,
    selectedKey: state.selectedActionKey,
    showExpand: state.showExpand,
    qosControls: state.actionQosControls,
    modeLinked: state.actionQosModeLinked,
    onModeLinkChange: state.setActionQosModeLinked,
    onClose: state.onClose,
    timeoutSec: state.goalTimeoutSec,
    visibleActions: state.visibleCallableActions,
  }
}

export function serviceExecutionViewProps(state) {
  return {
    busy: state.serviceCallBusy,
    calls: state.serviceCallHistory,
    expanded: state.expanded,
    importableOnly: state.serviceImportableOnly,
    onExecute: state.executeServiceCall,
    onFieldChange: (name, value) => state.setRequestValues((current) => ({ ...current, [name]: value })),
    onImportableOnlyChange: state.setServiceImportableOnly,
    onRequestQosModeChange: state.setServiceRequestQosMode,
    onRequestQosProfileChange: state.setServiceRequestQosProfile,
    modeLinked: state.serviceQosModeLinked,
    onModeLinkChange: state.setServiceQosModeLinked,
    onClose: state.onClose,
    onSelect: state.setSelectedServiceKey,
    onTimeoutChange: state.setTimeoutSec,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    requestValues: state.requestValues,
    result: state.serviceCallResult,
    requestQosMode: state.serviceRequestQosMode,
    requestQosProfile: state.serviceRequestQosProfile,
    selected: state.selectedService,
    selectedKey: state.selectedServiceKey,
    services: state.callableServices,
    showExpand: state.showExpand,
    timeoutSec: state.timeoutSec,
    visibleServices: state.visibleCallableServices,
  }
}

export function topicExecutionViewProps(state) {
  return {
    activeContinuousPublish: state.activeContinuousPublish,
    busy: state.topicPublishBusy,
    expanded: state.expanded,
    history: state.visiblePublishHistory,
    importableOnly: state.topicImportableOnly,
    messageValues: state.topicMessageValues,
    messages: state.callableMessages,
    onContinuousStart: state.startSelectedContinuousTopicPublish,
    onContinuousStop: state.stopSelectedContinuousTopicPublish,
    onFieldChange: (name, value) => state.setTopicMessageValues((current) => ({ ...current, [name]: value })),
    onHzChange: state.setTopicPublishHz,
    onImportableOnlyChange: state.setTopicImportableOnly,
    onPublish: state.publishSelectedTopicMessage,
    onQosModeChange: state.setTopicQosMode,
    onQosProfileChange: state.setTopicQosProfile,
    modeLinked: state.topicQosModeLinked,
    onModeLinkChange: state.setTopicQosModeLinked,
    onClose: state.onClose,
    onResetHistory: state.resetSelectedTopicPublishHistory,
    onSelect: state.setSelectedMessageKey,
    onTopicNameChange: state.setTopicPublishName,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    publishGraphTopics: state.publishGraphTopics,
    publishHz: state.topicPublishHz,
    publishName: state.topicPublishName,
    publishDomainId: state.topicPublishDomainId,
    publishResult: state.topicPublishResult,
    publishWarning: state.topicPublishWarning,
    qosMode: state.topicQosMode,
    qosProfile: state.topicQosProfile,
    selected: state.selectedMessage,
    selectedKey: state.selectedMessageKey,
    showExpand: state.showExpand,
    visibleMessages: state.visibleCallableMessages,
  }
}

export function serviceServerViewProps(state) {
  return {
    active: state.active,
    busy: state.busy,
    calls: state.calls,
    expanded: state.expanded,
    importableOnly: state.importableOnly,
    onClose: state.onClose,
    onFieldChange: state.onFieldChange,
    onImportableOnlyChange: state.setImportableOnly,
    onSelect: state.select,
    onStart: state.start,
    onStop: state.stop,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    responseValues: state.responseValues,
    result: state.result,
    selected: state.selected,
    selectedKey: state.selectedKey,
    serverDomainId: state.serverDomainId,
    serverName: state.serverName,
    onServiceNameChange: state.setServerName,
    services: state.services,
    showExpand: state.showExpand,
    visibleServices: state.visibleServices,
  }
}

export function actionServerViewProps(state) {
  return {
    acceptCancels: state.acceptCancels,
    acceptGoals: state.acceptGoals,
    actionName: state.actionName,
    actions: state.actions,
    active: state.active,
    busy: state.busy,
    expanded: state.expanded,
    feedbackValues: state.feedbackValues,
    goals: state.goals,
    importableOnly: state.importableOnly,
    onActionNameChange: state.setActionName,
    onAcceptCancelsChange: state.setAcceptCancels,
    onAcceptGoalsChange: state.setAcceptGoals,
    onClose: state.onClose,
    onFieldChange: state.onFieldChange,
    onImportableOnlyChange: state.setImportableOnly,
    onSelect: state.select,
    onStart: state.start,
    onStop: state.stop,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    result: state.result,
    resultDelaySec: state.resultDelaySec,
    resultValues: state.resultValues,
    selected: state.selected,
    selectedKey: state.selectedKey,
    serverDomainId: state.serverDomainId,
    onResultDelayChange: state.setResultDelaySec,
    showExpand: state.showExpand,
    visibleActions: state.visibleActions,
  }
}
