export function actionExecutionViewProps(state) {
  return {
    actions: state.callableActions,
    busy: state.actionGoalBusy,
    expanded: state.expanded,
    goals: state.actionGoalHistory,
    goalValues: state.goalValues,
    importableOnly: state.actionImportableOnly,
    onExecute: state.executeActionGoal,
    onFieldChange: (name, value) => state.setGoalValues((current) => ({ ...current, [name]: value })),
    onImportableOnlyChange: state.setActionImportableOnly,
    onSelect: state.setSelectedActionKey,
    onTimeoutChange: state.setGoalTimeoutSec,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    result: state.actionGoalResult,
    selected: state.selectedAction,
    selectedKey: state.selectedActionKey,
    showExpand: state.showExpand,
    timeoutSec: state.goalTimeoutSec,
    visibleActions: state.visibleCallableActions,
  }
}

export function serviceExecutionViewProps(state) {
  return {
    busy: state.serviceCallBusy,
    calls: state.serviceCallHistory,
    expanded: state.expanded,
    importableOnly: state.serviceImportableOnly,
    onExecute: state.executeServiceCall,
    onFieldChange: (name, value) => state.setRequestValues((current) => ({ ...current, [name]: value })),
    onImportableOnlyChange: state.setServiceImportableOnly,
    onSelect: state.setSelectedServiceKey,
    onTimeoutChange: state.setTimeoutSec,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    requestValues: state.requestValues,
    result: state.serviceCallResult,
    selected: state.selectedService,
    selectedKey: state.selectedServiceKey,
    services: state.callableServices,
    showExpand: state.showExpand,
    timeoutSec: state.timeoutSec,
    visibleServices: state.visibleCallableServices,
  }
}

export function topicExecutionViewProps(state) {
  return {
    activeContinuousPublish: state.activeContinuousPublish,
    busy: state.topicPublishBusy,
    expanded: state.expanded,
    history: state.visiblePublishHistory,
    importableOnly: state.topicImportableOnly,
    messageValues: state.topicMessageValues,
    messages: state.callableMessages,
    onContinuousStart: state.startSelectedContinuousTopicPublish,
    onContinuousStop: state.stopSelectedContinuousTopicPublish,
    onFieldChange: (name, value) => state.setTopicMessageValues((current) => ({ ...current, [name]: value })),
    onHzChange: state.setTopicPublishHz,
    onImportableOnlyChange: state.setTopicImportableOnly,
    onPublish: state.publishSelectedTopicMessage,
    onResetHistory: state.resetSelectedTopicPublishHistory,
    onSelect: state.setSelectedMessageKey,
    onTopicNameChange: state.setTopicPublishName,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    publishGraphTopics: state.publishGraphTopics,
    publishHz: state.topicPublishHz,
    publishName: state.topicPublishName,
    publishResult: state.topicPublishResult,
    publishWarning: state.topicPublishWarning,
    selected: state.selectedMessage,
    selectedKey: state.selectedMessageKey,
    showExpand: state.showExpand,
    visibleMessages: state.visibleCallableMessages,
  }
}

export function receiveWorkspaceViewProps(state) {
  return {
    action: {
      activeKey: state.activeReceiveActionKey,
      history: state.visibleReceiveActionHistory,
      items: state.callableActions,
      onRefresh: state.loadReceiveState,
      onResetAll: () => state.resetReceiveActions(false),
      onResetSelected: () => state.resetReceiveActions(true),
      onSearchChange: state.setReceiveActionSearch,
      onSelect: state.setSelectedActionKey,
      onStart: state.startSelectedActionReceive,
      onStop: state.stopSelectedActionReceive,
      search: state.receiveActionSearch,
      selectedKey: state.selectedReceiveActionKey,
      visibleItems: state.filteredReceiveActions,
    },
    expanded: state.expanded,
    mode: state.receiveMode,
    onModeChange: state.selectReceiveMode,
    onToggleExpanded: state.onToggleExpanded,
    open: state.open,
    service: {
      activeKey: state.activeReceiveServiceKey,
      history: state.visibleReceiveServiceHistory,
      items: state.callableServices,
      onRefresh: state.loadReceiveState,
      onResetAll: () => state.resetReceiveServices(false),
      onResetSelected: () => state.resetReceiveServices(true),
      onSearchChange: state.setReceiveServiceSearch,
      onSelect: state.setSelectedServiceKey,
      onStart: state.startSelectedServiceReceive,
      onStop: state.stopSelectedServiceReceive,
      search: state.receiveServiceSearch,
      selectedKey: state.selectedReceiveServiceKey,
      visibleItems: state.filteredReceiveServices,
    },
    topic: {
      allMessages: state.callableMessages,
      allTopics: state.availableTopics,
      filteredTopics: state.filteredReceiveTopics,
      importableOnly: state.topicImportableOnly,
      onImportableOnlyChange: state.setTopicImportableOnly,
      onMessageSelect: state.setSelectedMessageKey,
      onRefresh: state.loadReceiveState,
      onResetAll: state.resetAllTopicReceiveHistory,
      onResetSelected: state.resetSelectedTopicReceiveHistory,
      onSearchChange: state.setReceiveTopicSearch,
      onStart: state.startSelectedTopicReceive,
      onStop: state.stopSelectedTopicReceive,
      onTopicNameChange: state.setSelectedReceiveTopic,
      receiveHistory: state.visibleReceiveTopicHistory,
      receiving: state.selectedTopicReceiving,
      receivingTopics: state.receiveTopics,
      search: state.receiveTopicSearch,
      selectedMessage: state.selectedMessage,
      selectedMessageKey: state.selectedMessageKey,
      selectedTopic: state.selectedReceiveTopic,
      visibleMessages: state.visibleCallableMessages,
    },
  }
}

export function managementViewProps(state) {
  return {
    buildFailure: {
      applying: state.applying,
      buildLogTail: state.buildLogTail,
      busy: state.busy,
      onApply: state.applyUploadedInterfaces,
      onRegenerate: state.regenerateUploadedInterfacesCmake,
      onToggle: state.toggleBuildLog,
      open: state.showBuildLog,
      visible: state.applyStatus?.build_status === 'failed',
    },
    manual: {
      disabled: state.disabled,
      editingManualDefinition: state.editingManualDefinition,
      manualDefinition: state.manualDefinition,
      manualKind: state.manualKind,
      manualMode: state.manualMode,
      manualType: state.manualType,
      manualTypeName: state.manualTypeName,
      onCancelEdit: () => state.setEditingManualDefinition(null),
      onDefinitionChange: state.setManualDefinition,
      onKindChange: state.setManualKind,
      onModeChange: state.setManualMode,
      onSubmitDefinition: state.submitManualDefinition,
      onSubmitType: state.submitManualType,
      onTypeChange: state.setManualType,
      onTypeNameChange: state.setManualTypeName,
      onValidateDefinition: state.validateCurrentManualDefinition,
      open: state.showManualInput,
    },
    packages: {
      expanded: state.expanded,
      onDelete: state.handleRemovePackage,
      onToggleExpanded: state.toggleWorkspaceExpanded,
      open: state.showPackages,
      packages: state.packages,
    },
    registry: {
      onDelete: state.handleRemoveRegistryEntry,
      onDeleteManual: state.handleRemoveManualDefinition,
      onEditManual: state.startEditManualDefinition,
      open: state.showRegistry,
      recentDeletedRegistry: state.recentDeletedRegistry,
      registry: state.registry,
    },
    toolbar: {
      applying: state.applying,
      busy: state.busy,
      disabled: state.disabled,
      feedback: state.feedback,
      inputRef: state.inputRef,
      onApply: state.applyUploadedInterfaces,
      onFile: state.handleFile,
      onOpenAction: state.openActionPanel,
      onOpenPackages: state.openPackages,
      onOpenReceive: state.openReceivePanel,
      onOpenRegistry: state.openRegistry,
      onOpenService: state.openServicePanel,
      onOpenTopic: state.openTopicPanel,
      onPackageFile: state.handlePackageFile,
      onPackageFolder: state.handlePackageFolder,
      onReplaceChange: state.setReplacePackage,
      onToggleManual: () => state.setShowManualInput((value) => !value),
      packageFolderInputRef: state.packageFolderInputRef,
      packageInputRef: state.packageInputRef,
      reloadPhase: state.reloadPhase,
      replacePackage: state.replacePackage,
      websocketStatus: state.websocketStatus,
    },
  }
}
