import {
  actionExecutionViewProps,
  actionServerViewProps,
  serviceExecutionViewProps,
  serviceServerViewProps,
  topicExecutionViewProps,
} from './executionViewProps.js'
import { receiveWorkspaceViewProps } from './receiveViewProps.js'

export function interfaceExecutionViews({
  action,
  actionServer,
  availableTopics,
  panel,
  qos,
  receive,
  service,
  serviceServer,
  topic,
}) {
  return {
    actionExecution: actionExecutionViewProps({
      actionGoalBusy: action.busy,
      actionGoalHistory: action.history,
      actionGoalResult: action.result,
      actionImportableOnly: action.importableOnly,
      actionQosControls: qos.linkedActionExecutionQosControls,
      actionQosModeLinked: qos.actionQosLink.linked,
      callableActions: action.actions,
      closeExecutionPanels: panel.closeExecutionPanels,
      executeActionGoal: action.execute,
      expanded: panel.expanded,
      goalTimeoutSec: action.timeoutSec,
      goalValues: action.goalValues,
      onClose: panel.closeExecutionPanels,
      onToggleExpanded: panel.toggleWorkspaceExpanded,
      open: panel.showCallableActions,
      selectedAction: action.selected,
      selectedActionKey: action.selectedKey,
      setActionImportableOnly: action.setImportableOnly,
      setActionQosModeLinked: qos.actionQosLink.linkFromExecution,
      setGoalTimeoutSec: action.setTimeoutSec,
      setGoalValues: action.setGoalValues,
      setSelectedActionKey: action.select,
      showExpand: panel.showReceivePanel && receive.mode === 'action',
      visibleCallableActions: action.visibleActions,
    }),
    receive: receiveWorkspaceViewProps({
      activeReceiveActionKey: receive.activeActionKey,
      activeReceiveServiceKey: receive.activeServiceKey,
      actionQosControls: qos.linkedActionReceiveQosControls,
      actionQosModeLinked: qos.actionQosLink.linked,
      availableTopics,
      callableActions: receive.actions,
      callableMessages: receive.messages,
      callableServices: receive.services,
      closeReceivePanel: panel.closeReceivePanel,
      expanded: panel.expanded,
      filteredReceiveActions: receive.filteredActions,
      filteredReceiveServices: receive.filteredServices,
      filteredReceiveTopics: receive.filteredTopics,
      loadReceiveState: receive.load,
      onClose: panel.closeReceivePanel,
      onToggleExpanded: panel.toggleWorkspaceExpanded,
      open: panel.showReceivePanel,
      receiveActionSearch: receive.actionSearch,
      receiveMode: receive.mode,
      receiveServiceSearch: receive.serviceSearch,
      receiveTopicSearch: receive.topicSearch,
      receiveTopics: receive.topics,
      resetAllTopicReceiveHistory: receive.resetAllTopics,
      resetReceiveActions: receive.resetActions,
      resetReceiveServices: receive.resetServices,
      resetSelectedTopicReceiveHistory: receive.resetSelectedTopic,
      selectReceiveMode: panel.selectReceiveMode,
      selectedMessage: receive.selectedMessage,
      selectedMessageKey: receive.selectedMessageKey,
      selectedReceiveActionKey: receive.selectedReceiveActionKey,
      selectedReceiveServiceKey: receive.selectedReceiveServiceKey,
      selectedReceiveTopic: receive.selectedTopic,
      selectedReceiveTopicDomainId: receive.selectedDomainId,
      selectedTopicReceiving: receive.selectedTopicReceiving,
      serviceQosModeLinked: qos.serviceQosLink.linked,
      serviceResponseQosMode: service.responseQosMode,
      serviceResponseQosProfile: service.responseQosProfile,
      setActionQosModeLinked: qos.actionQosLink.linkFromReceive,
      setReceiveActionSearch: receive.setActionSearch,
      setReceiveServiceSearch: receive.setServiceSearch,
      setReceiveTopicSearch: receive.setTopicSearch,
      setSelectedActionKey: receive.setSelectedReceiveActionKey,
      setSelectedMessageKey: receive.setSelectedMessageKey,
      setSelectedReceiveTopic: receive.changeTopic,
      setSelectedServiceKey: receive.setSelectedReceiveServiceKey,
      setServiceQosModeLinked: qos.serviceQosLink.linkFromReceive,
      setServiceResponseQosMode: qos.serviceQosLink.changeReceiveMode,
      setServiceResponseQosProfile: (profile) => qos.serviceQosLink.changeReceiveProfile('service', profile),
      setTopicImportableOnly: receive.setMessageImportableOnly,
      setTopicQosMode: qos.topicQosLink.changeReceiveMode,
      setTopicQosModeLinked: qos.topicQosLink.linkFromReceive,
      setTopicQosProfile: (profile) => qos.topicQosLink.changeReceiveProfile('topic', profile),
      startSelectedActionReceive: receive.startAction,
      startSelectedServiceReceive: receive.startService,
      startSelectedTopicReceive: receive.startTopic,
      stopSelectedActionReceive: receive.stopAction,
      stopSelectedServiceReceive: receive.stopService,
      stopSelectedTopicReceive: receive.stopTopic,
      topicImportableOnly: receive.messageImportableOnly,
      topicQosMode: receive.qosMode,
      topicQosModeLinked: qos.topicQosLink.linked,
      topicQosProfile: receive.qosProfile,
      visibleCallableMessages: receive.visibleMessages,
      visibleReceiveActionHistory: receive.visibleActionHistory,
      visibleReceiveServiceHistory: receive.visibleServiceHistory,
      visibleReceiveTopicHistory: receive.visibleTopicHistory,
    }),
    serviceExecution: serviceExecutionViewProps({
      callableServices: service.services,
      executeServiceCall: service.execute,
      expanded: panel.expanded,
      onClose: panel.closeExecutionPanels,
      onToggleExpanded: panel.toggleWorkspaceExpanded,
      open: panel.showCallableServices,
      requestValues: service.requestValues,
      selectedService: service.selected,
      selectedServiceKey: service.selectedKey,
      serviceCallBusy: service.busy,
      serviceCallHistory: service.history,
      serviceCallResult: service.result,
      serviceImportableOnly: service.importableOnly,
      serviceQosModeLinked: qos.serviceQosLink.linked,
      serviceRequestQosMode: service.requestQosMode,
      serviceRequestQosProfile: service.requestQosProfile,
      setRequestValues: service.setRequestValues,
      setSelectedServiceKey: service.select,
      setServiceImportableOnly: service.setImportableOnly,
      setServiceQosModeLinked: qos.serviceQosLink.linkFromExecution,
      setServiceRequestQosMode: qos.serviceQosLink.changeExecutionMode,
      setServiceRequestQosProfile: (profile) => qos.serviceQosLink.changeExecutionProfile('service', profile),
      setTimeoutSec: service.setTimeoutSec,
      showExpand: panel.showReceivePanel && receive.mode === 'service',
      timeoutSec: service.timeoutSec,
      visibleCallableServices: service.visibleServices,
    }),
    topicExecution: topicExecutionViewProps({
      activeContinuousPublish: topic.activeContinuousPublish,
      callableMessages: topic.messages,
      expanded: panel.expanded,
      onClose: panel.closeExecutionPanels,
      onToggleExpanded: panel.toggleWorkspaceExpanded,
      open: panel.showCallableTopics,
      publishGraphTopics: topic.publishGraphTopics,
      publishSelectedTopicMessage: topic.publish,
      resetSelectedTopicPublishHistory: topic.resetHistory,
      selectedMessage: topic.selected,
      selectedMessageKey: topic.selectedKey,
      setSelectedMessageKey: topic.select,
      setTopicImportableOnly: topic.setImportableOnly,
      setTopicMessageValues: topic.setMessageValues,
      setTopicPublishHz: topic.setPublishHz,
      setTopicPublishName: topic.changePublishName,
      setTopicQosMode: qos.topicQosLink.changeExecutionMode,
      setTopicQosModeLinked: qos.topicQosLink.linkFromExecution,
      setTopicQosProfile: (profile) => qos.topicQosLink.changeExecutionProfile('topic', profile),
      showExpand: panel.showReceivePanel && receive.mode === 'topic',
      startSelectedContinuousTopicPublish: topic.startContinuous,
      stopSelectedContinuousTopicPublish: topic.stopContinuous,
      topicImportableOnly: topic.importableOnly,
      topicMessageValues: topic.messageValues,
      topicPublishBusy: topic.busy,
      topicPublishHz: topic.publishHz,
      topicPublishName: topic.publishName,
      topicPublishDomainId: topic.publishDomainId,
      topicPublishResult: topic.result,
      topicPublishWarning: topic.publishWarning,
      topicQosMode: topic.qosMode,
      topicQosModeLinked: qos.topicQosLink.linked,
      topicQosProfile: topic.qosProfile,
      visibleCallableMessages: topic.visibleMessages,
      visiblePublishHistory: topic.visibleHistory,
    }),
    serviceServer: serviceServer ? serviceServerViewProps({
      ...serviceServer,
      expanded: panel.expanded,
      onClose: panel.closeExecutionPanels,
      onToggleExpanded: panel.toggleWorkspaceExpanded,
      open: panel.showCallableServiceServer,
      showExpand: true,
    }) : { open: false },
    actionServer: actionServer ? actionServerViewProps({
      ...actionServer,
      expanded: panel.expanded,
      onClose: panel.closeExecutionPanels,
      onToggleExpanded: panel.toggleWorkspaceExpanded,
      open: panel.showCallableActionServer,
      showExpand: true,
    }) : { open: false },
  }
}
