export function managementViewProps(state) {
  return {
    buildFailure: {
      applying: state.applying,
      buildLogTail: state.buildLogTail,
      busy: state.busy,
      onApply: state.applyUploadedInterfaces,
      onRegenerate: state.regenerateUploadedInterfacesCmake,
      onToggle: state.toggleBuildLog,
      open: state.showBuildLog,
      visible: state.applyStatus?.build_status === 'failed',
    },
    manual: {
      disabled: state.disabled,
      editingManualDefinition: state.editingManualDefinition,
      manualDefinition: state.manualDefinition,
      manualKind: state.manualKind,
      manualMode: state.manualMode,
      manualType: state.manualType,
      manualTypeName: state.manualTypeName,
      onCancelEdit: () => state.setEditingManualDefinition(null),
      onDefinitionChange: state.setManualDefinition,
      onKindChange: state.setManualKind,
      onModeChange: state.setManualMode,
      onSubmitDefinition: state.submitManualDefinition,
      onSubmitType: state.submitManualType,
      onTypeChange: state.setManualType,
      onTypeNameChange: state.setManualTypeName,
      onValidateDefinition: state.validateCurrentManualDefinition,
      open: state.showManualInput,
    },
    packages: {
      expanded: state.expanded,
      onDelete: state.handleRemovePackage,
      onToggleExpanded: state.toggleWorkspaceExpanded,
      open: state.showPackages,
      packages: state.packages,
    },
    registry: {
      onDelete: state.handleRemoveRegistryEntry,
      onDeleteManual: state.handleRemoveManualDefinition,
      onEditManual: state.startEditManualDefinition,
      open: state.showRegistry,
      recentDeletedRegistry: state.recentDeletedRegistry,
      registry: state.registry,
    },
    toolbar: {
      applying: state.applying,
      busy: state.busy,
      disabled: state.disabled,
      feedback: state.feedback,
      inputRef: state.inputRef,
      onApply: state.applyUploadedInterfaces,
      onFile: state.handleFile,
      onOpenAction: state.openActionPanel,
      onOpenPackages: state.openPackages,
      onOpenReceive: state.openReceivePanel,
      onOpenRegistry: state.openRegistry,
      onOpenService: state.openServicePanel,
      onOpenTopic: state.openTopicPanel,
      onPackageFile: state.handlePackageFile,
      onPackageFolder: state.handlePackageFolder,
      onReplaceChange: state.setReplacePackage,
      onToggleManual: () => state.setShowManualInput((value) => !value),
      packageFolderInputRef: state.packageFolderInputRef,
      packageInputRef: state.packageInputRef,
      reloadPhase: state.reloadPhase,
      replacePackage: state.replacePackage,
      websocketStatus: state.websocketStatus,
    },
  }
}
